{
    'name': 'Réservation Logement avec Billetweb',
    'version': '17.0.1.0.0',
    'category': 'Sales',
    'summary': 'Gestion des réservations de logements avec paiement Billetweb',
    'depends': ['base', 'product', 'website', 'queue_job', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'data/booking_config_data.xml',
        'views/assets.xml',
        # 'views/booking_config_views.xml',
        'views/product_template_views.xml',
        'views/booking_views.xml',
        'views/website_booking_templates.xml',
        "views/res_config_settings_views.xml",
        'data/email_templates.xml',
    ],
    "post_init_hook": "post_init_hook",
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
