from . import res_partner
from . import config_settings
from . import tarif_historique
from . import ordonnance
from . import acte_type
from . import feuille_modele
from . import feuille_soins
from . import bordereau
from . import bordereau_modele
from . import api_usage
from . import patient_config
