from . import res_partner
from . import patient
from . import praticien
from . import config_settings
from . import tarif_historique
from . import ordonnance
from . import acte_type
from . import feuille_modele
from . import feuille_soins
from . import bordereau
