{
    'name': 'OS Auxiliaire Médical',
    'version': '17.0.6.0.0',
    'summary': 'Gestion des feuilles de soins et bordereaux CPS Polynésie française',
    'author': 'OpalSea',
    'website': 'https://www.opalsea.site',
    'category': 'Healthcare',
    'license': 'LGPL-3',
    'depends': ['base', 'mail', 'account', 'partner_firstname', 'partner_contact_birthdate'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'security/ir_rule_multi_company.xml',

        'data/ir_sequence_data.xml',
        'data/res_partner_category_data.xml',
        'data/cps_acte_type_orthophoniste_data.xml',
        'data/cps_acte_type_orthoptiste_data.xml',
        'data/cps_acte_type_pedicure_data.xml',
        'data/cps_acte_type_infirmier_data.xml',
        'data/cps_acte_type_kinesitherapeute_data.xml',

        'views/res_partner_cps_views.xml',
        'views/acte_type_server_action.xml',
        'views/acte_type_views.xml',
        'views/feuille_modele_views.xml',
        'views/ordonnance_views.xml',
        'views/feuille_soins_views.xml',
        'views/bordereau_views.xml',
        'views/tarif_historique_views.xml',
        'views/config_settings_views.xml',
        'views/menu_views.xml',

        'report/report_bordereau.xml',
        'report/report_feuille_soins.xml',

        'wizards/wizard_bordereau_views.xml',
        'wizards/wizard_date_selection_views.xml',
        'wizards/wizard_ocr_ordonnance_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'icon': 'static/description/icon.png',
}
